services:
  postgres_db:
    image: postgres:15
    container_name: logidata_postgres
    restart: always
    environment:
      # Usamos las variables definidas en el .env
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./data:/home/csv_files